// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma contract emit'.
// To regenerate, run: prisma contract emit
import type { CodecTypes as PgTypes } from '@prisma/orm-postgres/target/codec-types';
import type { QueryOperationTypes as PgTargetQueryOps } from '@prisma/orm-postgres/target/operation-types';

import type {
  ContractWithTypeMaps,
  RelationKeys,
  TypeMaps as TypeMapsType,
} from '@prisma/orm-postgres/family-contract/types';
import type {
  Contract as ContractType,
  ExecutionHashBase,
  NamespaceId,
  ProfileHashBase,
  StorageHashBase,
} from '@prisma/orm-postgres/contract/types';

export type StorageHash =
  StorageHashBase<'8b52836f9df6296a3126735430925e93f3763ead99a9a4ee4cbe90a897f0b597'>;
export type ExecutionHash =
  ExecutionHashBase<'4887868d721e35957d45f15b074b53c8942704cb83ebb422107171347071b0ff'>;
export type ProfileHash =
  ProfileHashBase<'3916f444a8a17ad749191acf9e08dad97d1a327b88c2f1d45d12f240296aa8b2'>;

export type CodecTypes = PgTypes;
export type LaneCodecTypes = CodecTypes;
export type QueryOperationTypes = PgTargetQueryOps<CodecTypes>;
export type AggregateTypes = {
  readonly avg: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
    };
  };
  readonly avgDecimal: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
    };
  };
  readonly count: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
  };
  readonly countBigInt: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
  };
  readonly max: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-date@1': {
        readonly output: 'pg/timestamptz-date@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly min: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-date@1': {
        readonly output: 'pg/timestamptz-date@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly sum: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
    };
  };
  readonly sumBigInt: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
    };
  };
};
type DefaultLiteralValue<CodecId extends string, Encoded> = CodecId extends keyof CodecTypes
  ? Encoded extends CodecTypes[CodecId]['json']
    ? Encoded
    : CodecTypes[CodecId]['json']
  : Encoded;

export type FieldOutputTypes = {
  readonly public: {
    readonly AuditLog: {
      readonly action: CodecTypes['pg/text@1']['output'];
      readonly actorId: CodecTypes['pg/uuid@1']['output'] | null;
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly entityId: CodecTypes['pg/text@1']['output'] | null;
      readonly entityType: CodecTypes['pg/text@1']['output'] | null;
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly ip: CodecTypes['pg/text@1']['output'] | null;
      readonly metadata: CodecTypes['pg/text@1']['output'] | null;
      readonly requestId: CodecTypes['pg/text@1']['output'] | null;
    };
    readonly Permission: {
      readonly action: CodecTypes['pg/text@1']['output'];
      readonly code: CodecTypes['pg/text@1']['output'];
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly description: CodecTypes['pg/text@1']['output'];
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly module: CodecTypes['pg/text@1']['output'];
      readonly name: CodecTypes['pg/text@1']['output'];
    };
    readonly Role: {
      readonly code: CodecTypes['pg/text@1']['output'];
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly description: CodecTypes['pg/text@1']['output'];
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly isSystem: CodecTypes['pg/bool@1']['output'];
      readonly name: CodecTypes['pg/text@1']['output'];
      readonly status: 'ACTIVE' | 'DISABLED';
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['output'];
    };
    readonly RolePermission: {
      readonly grantedAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly permissionId: CodecTypes['pg/uuid@1']['output'];
      readonly roleId: CodecTypes['pg/uuid@1']['output'];
    };
    readonly User: {
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly email: CodecTypes['pg/text@1']['output'];
      readonly employeeCode: CodecTypes['pg/text@1']['output'];
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly lastLoginAt: CodecTypes['pg/timestamptz-string@1']['output'] | null;
      readonly name: CodecTypes['pg/text@1']['output'];
      readonly passwordHash: CodecTypes['pg/text@1']['output'];
      readonly phone: CodecTypes['pg/text@1']['output'] | null;
      readonly status: 'ACTIVE' | 'DISABLED';
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['output'];
    };
    readonly UserRole: {
      readonly grantedAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly roleId: CodecTypes['pg/uuid@1']['output'];
      readonly userId: CodecTypes['pg/uuid@1']['output'];
    };
    readonly UserSession: {
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly expiresAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly ip: CodecTypes['pg/text@1']['output'] | null;
      readonly lastUsedAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly revokedAt: CodecTypes['pg/timestamptz-string@1']['output'] | null;
      readonly revokedBy: CodecTypes['pg/uuid@1']['output'] | null;
      readonly tokenHash: CodecTypes['pg/text@1']['output'];
      readonly userAgent: CodecTypes['pg/text@1']['output'] | null;
      readonly userId: CodecTypes['pg/uuid@1']['output'];
    };
  };
};
export type FieldInputTypes = {
  readonly public: {
    readonly AuditLog: {
      readonly action: CodecTypes['pg/text@1']['input'];
      readonly actorId: CodecTypes['pg/uuid@1']['input'] | null;
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly entityId: CodecTypes['pg/text@1']['input'] | null;
      readonly entityType: CodecTypes['pg/text@1']['input'] | null;
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly ip: CodecTypes['pg/text@1']['input'] | null;
      readonly metadata: CodecTypes['pg/text@1']['input'] | null;
      readonly requestId: CodecTypes['pg/text@1']['input'] | null;
    };
    readonly Permission: {
      readonly action: CodecTypes['pg/text@1']['input'];
      readonly code: CodecTypes['pg/text@1']['input'];
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly description: CodecTypes['pg/text@1']['input'];
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly module: CodecTypes['pg/text@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'];
    };
    readonly Role: {
      readonly code: CodecTypes['pg/text@1']['input'];
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly description: CodecTypes['pg/text@1']['input'];
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly isSystem: CodecTypes['pg/bool@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'];
      readonly status: 'ACTIVE' | 'DISABLED';
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['input'];
    };
    readonly RolePermission: {
      readonly grantedAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly permissionId: CodecTypes['pg/uuid@1']['input'];
      readonly roleId: CodecTypes['pg/uuid@1']['input'];
    };
    readonly User: {
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly email: CodecTypes['pg/text@1']['input'];
      readonly employeeCode: CodecTypes['pg/text@1']['input'];
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly lastLoginAt: CodecTypes['pg/timestamptz-string@1']['input'] | null;
      readonly name: CodecTypes['pg/text@1']['input'];
      readonly passwordHash: CodecTypes['pg/text@1']['input'];
      readonly phone: CodecTypes['pg/text@1']['input'] | null;
      readonly status: 'ACTIVE' | 'DISABLED';
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['input'];
    };
    readonly UserRole: {
      readonly grantedAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly roleId: CodecTypes['pg/uuid@1']['input'];
      readonly userId: CodecTypes['pg/uuid@1']['input'];
    };
    readonly UserSession: {
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly expiresAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly ip: CodecTypes['pg/text@1']['input'] | null;
      readonly lastUsedAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly revokedAt: CodecTypes['pg/timestamptz-string@1']['input'] | null;
      readonly revokedBy: CodecTypes['pg/uuid@1']['input'] | null;
      readonly tokenHash: CodecTypes['pg/text@1']['input'];
      readonly userAgent: CodecTypes['pg/text@1']['input'] | null;
      readonly userId: CodecTypes['pg/uuid@1']['input'];
    };
  };
};
export type StorageColumnTypes = {
  readonly public: {
    readonly erp_audit_logs: {
      readonly action: CodecTypes['pg/text@1']['output'];
      readonly actorId: CodecTypes['pg/uuid@1']['output'] | null;
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly entityId: CodecTypes['pg/text@1']['output'] | null;
      readonly entityType: CodecTypes['pg/text@1']['output'] | null;
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly ip: CodecTypes['pg/text@1']['output'] | null;
      readonly metadata: CodecTypes['pg/text@1']['output'] | null;
      readonly requestId: CodecTypes['pg/text@1']['output'] | null;
    };
    readonly erp_permissions: {
      readonly action: CodecTypes['pg/text@1']['output'];
      readonly code: CodecTypes['pg/text@1']['output'];
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly description: CodecTypes['pg/text@1']['output'];
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly module: CodecTypes['pg/text@1']['output'];
      readonly name: CodecTypes['pg/text@1']['output'];
    };
    readonly erp_role_permissions: {
      readonly grantedAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly permissionId: CodecTypes['pg/uuid@1']['output'];
      readonly roleId: CodecTypes['pg/uuid@1']['output'];
    };
    readonly erp_roles: {
      readonly code: CodecTypes['pg/text@1']['output'];
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly description: CodecTypes['pg/text@1']['output'];
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly isSystem: CodecTypes['pg/bool@1']['output'];
      readonly name: CodecTypes['pg/text@1']['output'];
      readonly status: 'ACTIVE' | 'DISABLED';
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['output'];
    };
    readonly erp_user_roles: {
      readonly grantedAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly roleId: CodecTypes['pg/uuid@1']['output'];
      readonly userId: CodecTypes['pg/uuid@1']['output'];
    };
    readonly erp_user_sessions: {
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly expiresAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly ip: CodecTypes['pg/text@1']['output'] | null;
      readonly lastUsedAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly revokedAt: CodecTypes['pg/timestamptz-string@1']['output'] | null;
      readonly revokedBy: CodecTypes['pg/uuid@1']['output'] | null;
      readonly tokenHash: CodecTypes['pg/text@1']['output'];
      readonly userAgent: CodecTypes['pg/text@1']['output'] | null;
      readonly userId: CodecTypes['pg/uuid@1']['output'];
    };
    readonly erp_users: {
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly email: CodecTypes['pg/text@1']['output'];
      readonly employeeCode: CodecTypes['pg/text@1']['output'];
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly lastLoginAt: CodecTypes['pg/timestamptz-string@1']['output'] | null;
      readonly name: CodecTypes['pg/text@1']['output'];
      readonly passwordHash: CodecTypes['pg/text@1']['output'];
      readonly phone: CodecTypes['pg/text@1']['output'] | null;
      readonly status: 'ACTIVE' | 'DISABLED';
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['output'];
    };
  };
};
export type StorageColumnInputTypes = {
  readonly public: {
    readonly erp_audit_logs: {
      readonly action: CodecTypes['pg/text@1']['input'];
      readonly actorId: CodecTypes['pg/uuid@1']['input'] | null;
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly entityId: CodecTypes['pg/text@1']['input'] | null;
      readonly entityType: CodecTypes['pg/text@1']['input'] | null;
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly ip: CodecTypes['pg/text@1']['input'] | null;
      readonly metadata: CodecTypes['pg/text@1']['input'] | null;
      readonly requestId: CodecTypes['pg/text@1']['input'] | null;
    };
    readonly erp_permissions: {
      readonly action: CodecTypes['pg/text@1']['input'];
      readonly code: CodecTypes['pg/text@1']['input'];
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly description: CodecTypes['pg/text@1']['input'];
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly module: CodecTypes['pg/text@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'];
    };
    readonly erp_role_permissions: {
      readonly grantedAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly permissionId: CodecTypes['pg/uuid@1']['input'];
      readonly roleId: CodecTypes['pg/uuid@1']['input'];
    };
    readonly erp_roles: {
      readonly code: CodecTypes['pg/text@1']['input'];
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly description: CodecTypes['pg/text@1']['input'];
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly isSystem: CodecTypes['pg/bool@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'];
      readonly status: 'ACTIVE' | 'DISABLED';
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['input'];
    };
    readonly erp_user_roles: {
      readonly grantedAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly roleId: CodecTypes['pg/uuid@1']['input'];
      readonly userId: CodecTypes['pg/uuid@1']['input'];
    };
    readonly erp_user_sessions: {
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly expiresAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly ip: CodecTypes['pg/text@1']['input'] | null;
      readonly lastUsedAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly revokedAt: CodecTypes['pg/timestamptz-string@1']['input'] | null;
      readonly revokedBy: CodecTypes['pg/uuid@1']['input'] | null;
      readonly tokenHash: CodecTypes['pg/text@1']['input'];
      readonly userAgent: CodecTypes['pg/text@1']['input'] | null;
      readonly userId: CodecTypes['pg/uuid@1']['input'];
    };
    readonly erp_users: {
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly email: CodecTypes['pg/text@1']['input'];
      readonly employeeCode: CodecTypes['pg/text@1']['input'];
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly lastLoginAt: CodecTypes['pg/timestamptz-string@1']['input'] | null;
      readonly name: CodecTypes['pg/text@1']['input'];
      readonly passwordHash: CodecTypes['pg/text@1']['input'];
      readonly phone: CodecTypes['pg/text@1']['input'] | null;
      readonly status: 'ACTIVE' | 'DISABLED';
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['input'];
    };
  };
};

export namespace Models {
  export type public_AuditLog = {
    action: CodecTypes['pg/text@1']['output'];
    actorId: CodecTypes['pg/uuid@1']['output'] | null;
    createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
    entityId: CodecTypes['pg/text@1']['output'] | null;
    entityType: CodecTypes['pg/text@1']['output'] | null;
    id: CodecTypes['pg/uuid@1']['output'];
    ip: CodecTypes['pg/text@1']['output'] | null;
    metadata: CodecTypes['pg/text@1']['output'] | null;
    requestId: CodecTypes['pg/text@1']['output'] | null;
    readonly [RelationKeys]?: never;
  };
  export type public_Permission = {
    action: CodecTypes['pg/text@1']['output'];
    code: CodecTypes['pg/text@1']['output'];
    createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
    description: CodecTypes['pg/text@1']['output'];
    id: CodecTypes['pg/uuid@1']['output'];
    module: CodecTypes['pg/text@1']['output'];
    name: CodecTypes['pg/text@1']['output'];
    rolePermissions: public_RolePermission[];
    readonly [RelationKeys]?: 'rolePermissions';
  };
  export type public_Role = {
    code: CodecTypes['pg/text@1']['output'];
    createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
    description: CodecTypes['pg/text@1']['output'];
    id: CodecTypes['pg/uuid@1']['output'];
    isSystem: CodecTypes['pg/bool@1']['output'];
    name: CodecTypes['pg/text@1']['output'];
    status: 'ACTIVE' | 'DISABLED';
    updatedAt: CodecTypes['pg/timestamptz-string@1']['output'];
    rolePermissions: public_RolePermission[];
    userRoles: public_UserRole[];
    readonly [RelationKeys]?: 'rolePermissions' | 'userRoles';
  };
  export type public_RolePermission = {
    grantedAt: CodecTypes['pg/timestamptz-string@1']['output'];
    id: CodecTypes['pg/uuid@1']['output'];
    permissionId: CodecTypes['pg/uuid@1']['output'];
    roleId: CodecTypes['pg/uuid@1']['output'];
    permission: public_Permission;
    role: public_Role;
    readonly [RelationKeys]?: 'permission' | 'role';
  };
  export type public_User = {
    createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
    email: CodecTypes['pg/text@1']['output'];
    employeeCode: CodecTypes['pg/text@1']['output'];
    id: CodecTypes['pg/uuid@1']['output'];
    lastLoginAt: CodecTypes['pg/timestamptz-string@1']['output'] | null;
    name: CodecTypes['pg/text@1']['output'];
    passwordHash: CodecTypes['pg/text@1']['output'];
    phone: CodecTypes['pg/text@1']['output'] | null;
    status: 'ACTIVE' | 'DISABLED';
    updatedAt: CodecTypes['pg/timestamptz-string@1']['output'];
    userRoles: public_UserRole[];
    readonly [RelationKeys]?: 'userRoles';
  };
  export type public_UserRole = {
    grantedAt: CodecTypes['pg/timestamptz-string@1']['output'];
    id: CodecTypes['pg/uuid@1']['output'];
    roleId: CodecTypes['pg/uuid@1']['output'];
    userId: CodecTypes['pg/uuid@1']['output'];
    role: public_Role;
    user: public_User;
    readonly [RelationKeys]?: 'role' | 'user';
  };
  export type public_UserSession = {
    createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
    expiresAt: CodecTypes['pg/timestamptz-string@1']['output'];
    id: CodecTypes['pg/uuid@1']['output'];
    ip: CodecTypes['pg/text@1']['output'] | null;
    lastUsedAt: CodecTypes['pg/timestamptz-string@1']['output'];
    revokedAt: CodecTypes['pg/timestamptz-string@1']['output'] | null;
    revokedBy: CodecTypes['pg/uuid@1']['output'] | null;
    tokenHash: CodecTypes['pg/text@1']['output'];
    userAgent: CodecTypes['pg/text@1']['output'] | null;
    userId: CodecTypes['pg/uuid@1']['output'];
    user: public_User;
    readonly [RelationKeys]?: 'user';
  };
}

export declare const models: {
  public: {
    AuditLog: Models.public_AuditLog;
    Permission: Models.public_Permission;
    Role: Models.public_Role;
    RolePermission: Models.public_RolePermission;
    User: Models.public_User;
    UserRole: Models.public_UserRole;
    UserSession: Models.public_UserSession;
  };
};

export type TypeMaps = TypeMapsType<
  CodecTypes,
  QueryOperationTypes,
  FieldOutputTypes,
  FieldInputTypes,
  StorageColumnTypes,
  StorageColumnInputTypes,
  AggregateTypes
>;

type ContractBase = Omit<
  ContractType<{
    readonly namespaces: {
      readonly public: {
        readonly id: 'public';
        readonly kind: 'postgres-schema';
        readonly entries: {
          readonly table: {
            readonly erp_audit_logs: {
              columns: {
                readonly action: {
                  readonly dataType: 'pg/text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly many: false;
                };
                readonly actorId: {
                  readonly dataType: 'pg/uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: true;
                  readonly many: false;
                };
                readonly createdAt: {
                  readonly dataType: 'pg/timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                  readonly many: false;
                };
                readonly entityId: {
                  readonly dataType: 'pg/text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                  readonly many: false;
                };
                readonly entityType: {
                  readonly dataType: 'pg/text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                  readonly many: false;
                };
                readonly id: {
                  readonly dataType: 'pg/uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                  readonly many: false;
                };
                readonly ip: {
                  readonly dataType: 'pg/text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                  readonly many: false;
                };
                readonly metadata: {
                  readonly dataType: 'pg/text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                  readonly many: false;
                };
                readonly requestId: {
                  readonly dataType: 'pg/text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                  readonly many: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'erp_audit_logs_action_idx_cd0d2116';
                  readonly prefix: 'erp_audit_logs_action_idx';
                  readonly columns: readonly ['action'];
                  readonly unique: false;
                },
                {
                  readonly name: 'erp_audit_logs_actorId_idx_a58f6b4b';
                  readonly prefix: 'erp_audit_logs_actorId_idx';
                  readonly columns: readonly ['actorId'];
                  readonly unique: false;
                },
                {
                  readonly name: 'erp_audit_logs_createdAt_idx_9575dbd7';
                  readonly prefix: 'erp_audit_logs_createdAt_idx';
                  readonly columns: readonly ['createdAt'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [];
            };
            readonly erp_permissions: {
              columns: {
                readonly action: {
                  readonly dataType: 'pg/text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly many: false;
                };
                readonly code: {
                  readonly dataType: 'pg/text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly many: false;
                };
                readonly createdAt: {
                  readonly dataType: 'pg/timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                  readonly many: false;
                };
                readonly description: {
                  readonly dataType: 'pg/text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly many: false;
                };
                readonly id: {
                  readonly dataType: 'pg/uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                  readonly many: false;
                };
                readonly module: {
                  readonly dataType: 'pg/text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly many: false;
                };
                readonly name: {
                  readonly dataType: 'pg/text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly many: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [{ readonly columns: readonly ['code'] }];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly erp_role_permissions: {
              columns: {
                readonly grantedAt: {
                  readonly dataType: 'pg/timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                  readonly many: false;
                };
                readonly id: {
                  readonly dataType: 'pg/uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                  readonly many: false;
                };
                readonly permissionId: {
                  readonly dataType: 'pg/uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                  readonly many: false;
                };
                readonly roleId: {
                  readonly dataType: 'pg/uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                  readonly many: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [{ readonly columns: readonly ['roleId', 'permissionId'] }];
              indexes: readonly [
                {
                  readonly name: 'erp_role_permissions_permissionId_idx_f46fcdf5';
                  readonly prefix: 'erp_role_permissions_permissionId_idx';
                  readonly columns: readonly ['permissionId'];
                  readonly unique: false;
                },
                {
                  readonly name: 'erp_role_permissions_roleId_idx_ffccc9a4';
                  readonly prefix: 'erp_role_permissions_roleId_idx';
                  readonly columns: readonly ['roleId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'erp_role_permissions';
                    readonly columns: readonly ['roleId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'erp_roles';
                    readonly columns: readonly ['id'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'erp_role_permissions';
                    readonly columns: readonly ['permissionId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'erp_permissions';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly erp_roles: {
              columns: {
                readonly code: {
                  readonly dataType: 'pg/text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly many: false;
                };
                readonly createdAt: {
                  readonly dataType: 'pg/timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                  readonly many: false;
                };
                readonly description: {
                  readonly dataType: 'pg/text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly many: false;
                };
                readonly id: {
                  readonly dataType: 'pg/uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                  readonly many: false;
                };
                readonly isSystem: {
                  readonly dataType: 'pg/bool';
                  readonly codecId: 'pg/bool@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/bool@1', false>;
                  };
                  readonly many: false;
                };
                readonly name: {
                  readonly dataType: 'pg/text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly many: false;
                };
                readonly status: {
                  readonly dataType: 'pg/text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/text@1', 'ACTIVE'>;
                  };
                  readonly many: false;
                };
                readonly updatedAt: {
                  readonly dataType: 'pg/timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                  readonly many: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [
                { readonly columns: readonly ['name'] },
                { readonly columns: readonly ['code'] },
              ];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly erp_user_roles: {
              columns: {
                readonly grantedAt: {
                  readonly dataType: 'pg/timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                  readonly many: false;
                };
                readonly id: {
                  readonly dataType: 'pg/uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                  readonly many: false;
                };
                readonly roleId: {
                  readonly dataType: 'pg/uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                  readonly many: false;
                };
                readonly userId: {
                  readonly dataType: 'pg/uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                  readonly many: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [{ readonly columns: readonly ['userId', 'roleId'] }];
              indexes: readonly [
                {
                  readonly name: 'erp_user_roles_roleId_idx_ffccc9a4';
                  readonly prefix: 'erp_user_roles_roleId_idx';
                  readonly columns: readonly ['roleId'];
                  readonly unique: false;
                },
                {
                  readonly name: 'erp_user_roles_userId_idx_a489d58a';
                  readonly prefix: 'erp_user_roles_userId_idx';
                  readonly columns: readonly ['userId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'erp_user_roles';
                    readonly columns: readonly ['userId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'erp_users';
                    readonly columns: readonly ['id'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'erp_user_roles';
                    readonly columns: readonly ['roleId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'erp_roles';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly erp_user_sessions: {
              columns: {
                readonly createdAt: {
                  readonly dataType: 'pg/timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                  readonly many: false;
                };
                readonly expiresAt: {
                  readonly dataType: 'pg/timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                  readonly many: false;
                };
                readonly id: {
                  readonly dataType: 'pg/uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                  readonly many: false;
                };
                readonly ip: {
                  readonly dataType: 'pg/text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                  readonly many: false;
                };
                readonly lastUsedAt: {
                  readonly dataType: 'pg/timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                  readonly many: false;
                };
                readonly revokedAt: {
                  readonly dataType: 'pg/timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: true;
                  readonly many: false;
                };
                readonly revokedBy: {
                  readonly dataType: 'pg/uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: true;
                  readonly many: false;
                };
                readonly tokenHash: {
                  readonly dataType: 'pg/text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly many: false;
                };
                readonly userAgent: {
                  readonly dataType: 'pg/text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                  readonly many: false;
                };
                readonly userId: {
                  readonly dataType: 'pg/uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                  readonly many: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [{ readonly columns: readonly ['tokenHash'] }];
              indexes: readonly [
                {
                  readonly name: 'erp_user_sessions_expiresAt_idx_6b6b8c10';
                  readonly prefix: 'erp_user_sessions_expiresAt_idx';
                  readonly columns: readonly ['expiresAt'];
                  readonly unique: false;
                },
                {
                  readonly name: 'erp_user_sessions_userId_idx_a489d58a';
                  readonly prefix: 'erp_user_sessions_userId_idx';
                  readonly columns: readonly ['userId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'erp_user_sessions';
                    readonly columns: readonly ['userId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'erp_users';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly erp_users: {
              columns: {
                readonly createdAt: {
                  readonly dataType: 'pg/timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                  readonly many: false;
                };
                readonly email: {
                  readonly dataType: 'pg/text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly many: false;
                };
                readonly employeeCode: {
                  readonly dataType: 'pg/text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly many: false;
                };
                readonly id: {
                  readonly dataType: 'pg/uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                  readonly many: false;
                };
                readonly lastLoginAt: {
                  readonly dataType: 'pg/timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: true;
                  readonly many: false;
                };
                readonly name: {
                  readonly dataType: 'pg/text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly many: false;
                };
                readonly passwordHash: {
                  readonly dataType: 'pg/text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly many: false;
                };
                readonly phone: {
                  readonly dataType: 'pg/text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                  readonly many: false;
                };
                readonly status: {
                  readonly dataType: 'pg/text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/text@1', 'ACTIVE'>;
                  };
                  readonly many: false;
                };
                readonly updatedAt: {
                  readonly dataType: 'pg/timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                  readonly many: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [
                { readonly columns: readonly ['employeeCode'] },
                { readonly columns: readonly ['email'] },
              ];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
          };
          readonly valueSet: {
            readonly RoleStatus: {
              readonly kind: 'valueSet';
              readonly values: readonly ['ACTIVE', 'DISABLED'];
            };
            readonly UserStatus: {
              readonly kind: 'valueSet';
              readonly values: readonly ['ACTIVE', 'DISABLED'];
            };
          };
        };
      };
    };
    readonly storageHash: StorageHash;
  }>,
  'roots' | 'domain'
> & {
  readonly target: 'postgres';
  readonly targetFamily: 'sql';
  readonly roots: {
    readonly erp_audit_logs: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'AuditLog';
    };
    readonly erp_permissions: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'Permission';
    };
    readonly erp_role_permissions: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'RolePermission';
    };
    readonly erp_roles: { readonly namespace: 'public' & NamespaceId; readonly model: 'Role' };
    readonly erp_user_roles: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'UserRole';
    };
    readonly erp_user_sessions: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'UserSession';
    };
    readonly erp_users: { readonly namespace: 'public' & NamespaceId; readonly model: 'User' };
  };
  readonly domain: {
    readonly namespaces: {
      readonly public: {
        readonly models: {
          readonly AuditLog: {
            readonly fields: {
              readonly action: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly actorId: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly entityId: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly entityType: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly ip: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly metadata: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly requestId: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: {
              readonly table: 'erp_audit_logs';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly action: { readonly column: 'action' };
                readonly actorId: { readonly column: 'actorId' };
                readonly createdAt: { readonly column: 'createdAt' };
                readonly entityId: { readonly column: 'entityId' };
                readonly entityType: { readonly column: 'entityType' };
                readonly id: { readonly column: 'id' };
                readonly ip: { readonly column: 'ip' };
                readonly metadata: { readonly column: 'metadata' };
                readonly requestId: { readonly column: 'requestId' };
              };
            };
          };
          readonly Permission: {
            readonly fields: {
              readonly action: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly code: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly description: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly module: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly name: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
            };
            readonly relations: {
              readonly rolePermissions: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'RolePermission';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['permissionId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'erp_permissions';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly action: { readonly column: 'action' };
                readonly code: { readonly column: 'code' };
                readonly createdAt: { readonly column: 'createdAt' };
                readonly description: { readonly column: 'description' };
                readonly id: { readonly column: 'id' };
                readonly module: { readonly column: 'module' };
                readonly name: { readonly column: 'name' };
              };
            };
          };
          readonly Role: {
            readonly fields: {
              readonly code: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly description: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly isSystem: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/bool@1' };
              };
              readonly name: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly status: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
            };
            readonly relations: {
              readonly rolePermissions: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'RolePermission';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['roleId'];
                };
              };
              readonly userRoles: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'UserRole';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['roleId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'erp_roles';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly code: { readonly column: 'code' };
                readonly createdAt: { readonly column: 'createdAt' };
                readonly description: { readonly column: 'description' };
                readonly id: { readonly column: 'id' };
                readonly isSystem: { readonly column: 'isSystem' };
                readonly name: { readonly column: 'name' };
                readonly status: { readonly column: 'status' };
                readonly updatedAt: { readonly column: 'updatedAt' };
              };
            };
          };
          readonly RolePermission: {
            readonly fields: {
              readonly grantedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly permissionId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly roleId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
            };
            readonly relations: {
              readonly permission: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Permission';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['permissionId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly role: {
                readonly to: { readonly namespace: 'public' & NamespaceId; readonly model: 'Role' };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['roleId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'erp_role_permissions';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly grantedAt: { readonly column: 'grantedAt' };
                readonly id: { readonly column: 'id' };
                readonly permissionId: { readonly column: 'permissionId' };
                readonly roleId: { readonly column: 'roleId' };
              };
            };
          };
          readonly User: {
            readonly fields: {
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly email: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly employeeCode: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly lastLoginAt: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly name: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly passwordHash: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly phone: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly status: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
            };
            readonly relations: {
              readonly userRoles: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'UserRole';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['userId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'erp_users';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly createdAt: { readonly column: 'createdAt' };
                readonly email: { readonly column: 'email' };
                readonly employeeCode: { readonly column: 'employeeCode' };
                readonly id: { readonly column: 'id' };
                readonly lastLoginAt: { readonly column: 'lastLoginAt' };
                readonly name: { readonly column: 'name' };
                readonly passwordHash: { readonly column: 'passwordHash' };
                readonly phone: { readonly column: 'phone' };
                readonly status: { readonly column: 'status' };
                readonly updatedAt: { readonly column: 'updatedAt' };
              };
            };
          };
          readonly UserRole: {
            readonly fields: {
              readonly grantedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly roleId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly userId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
            };
            readonly relations: {
              readonly role: {
                readonly to: { readonly namespace: 'public' & NamespaceId; readonly model: 'Role' };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['roleId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly user: {
                readonly to: { readonly namespace: 'public' & NamespaceId; readonly model: 'User' };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['userId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'erp_user_roles';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly grantedAt: { readonly column: 'grantedAt' };
                readonly id: { readonly column: 'id' };
                readonly roleId: { readonly column: 'roleId' };
                readonly userId: { readonly column: 'userId' };
              };
            };
          };
          readonly UserSession: {
            readonly fields: {
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly expiresAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly ip: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly lastUsedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly revokedAt: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly revokedBy: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly tokenHash: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly userAgent: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly userId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
            };
            readonly relations: {
              readonly user: {
                readonly to: { readonly namespace: 'public' & NamespaceId; readonly model: 'User' };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['userId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'erp_user_sessions';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly createdAt: { readonly column: 'createdAt' };
                readonly expiresAt: { readonly column: 'expiresAt' };
                readonly id: { readonly column: 'id' };
                readonly ip: { readonly column: 'ip' };
                readonly lastUsedAt: { readonly column: 'lastUsedAt' };
                readonly revokedAt: { readonly column: 'revokedAt' };
                readonly revokedBy: { readonly column: 'revokedBy' };
                readonly tokenHash: { readonly column: 'tokenHash' };
                readonly userAgent: { readonly column: 'userAgent' };
                readonly userId: { readonly column: 'userId' };
              };
            };
          };
        };
        readonly enum: {
          readonly RoleStatus: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'ACTIVE'; readonly value: 'ACTIVE' },
              { readonly name: 'DISABLED'; readonly value: 'DISABLED' },
            ];
          };
          readonly UserStatus: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'ACTIVE'; readonly value: 'ACTIVE' },
              { readonly name: 'DISABLED'; readonly value: 'DISABLED' },
            ];
          };
        };
      };
    };
  };
  readonly capabilities: {
    readonly postgres: {
      readonly distinctOn: true;
      readonly forKeyShare: true;
      readonly forNoKeyUpdate: true;
      readonly jsonAgg: true;
      readonly lateral: true;
      readonly limit: true;
      readonly orderBy: true;
      readonly returning: true;
    };
    readonly sql: {
      readonly checkConstraint: true;
      readonly defaultInInsert: true;
      readonly enums: true;
      readonly forShare: true;
      readonly forUpdate: true;
      readonly insertOnConflictSkip: true;
      readonly insertOnConflictWithoutTarget: true;
      readonly lateral: true;
      readonly lockNowait: true;
      readonly lockOf: true;
      readonly lockSkipLocked: true;
      readonly returning: true;
      readonly scalarList: true;
    };
  };
  readonly extensions: {};
  readonly execution: {
    readonly executionHash: ExecutionHash;
    readonly mutations: {
      readonly defaults: readonly [
        {
          readonly onCreate: { readonly id: 'uuidv4'; readonly kind: 'generator' };
          readonly ref: {
            readonly entry: 'erp_audit_logs';
            readonly field: 'id';
            readonly namespace: 'public';
          };
        },
        {
          readonly onCreate: { readonly id: 'uuidv4'; readonly kind: 'generator' };
          readonly ref: {
            readonly entry: 'erp_permissions';
            readonly field: 'id';
            readonly namespace: 'public';
          };
        },
        {
          readonly onCreate: { readonly id: 'uuidv4'; readonly kind: 'generator' };
          readonly ref: {
            readonly entry: 'erp_role_permissions';
            readonly field: 'id';
            readonly namespace: 'public';
          };
        },
        {
          readonly onCreate: { readonly id: 'uuidv4'; readonly kind: 'generator' };
          readonly ref: {
            readonly entry: 'erp_roles';
            readonly field: 'id';
            readonly namespace: 'public';
          };
        },
        {
          readonly onCreate: { readonly id: 'uuidv4'; readonly kind: 'generator' };
          readonly ref: {
            readonly entry: 'erp_user_roles';
            readonly field: 'id';
            readonly namespace: 'public';
          };
        },
        {
          readonly onCreate: { readonly id: 'uuidv4'; readonly kind: 'generator' };
          readonly ref: {
            readonly entry: 'erp_user_sessions';
            readonly field: 'id';
            readonly namespace: 'public';
          };
        },
        {
          readonly onCreate: { readonly id: 'uuidv4'; readonly kind: 'generator' };
          readonly ref: {
            readonly entry: 'erp_users';
            readonly field: 'id';
            readonly namespace: 'public';
          };
        },
      ];
    };
  };
  readonly meta: {};

  readonly profileHash: ProfileHash;
};

export type Contract = ContractWithTypeMaps<ContractBase, TypeMaps>;

export type Namespaces = Contract['storage']['namespaces'];
